# -- Image map
image:
  # -- Image registry
  registry: docker.io
  # -- Image repository
  repository: lucernae/django-sample
  # -- Image tag
  tag: "3.1"
  # -- Image pullPolicy
  pullPolicy: IfNotPresent

# -- (map) The deployment label
# @notationType -- yaml
labels:
  user/workload: "true"
  client-name: "my-boss"
  project-name: "awesome-project"
