before:
  hooks:
    - go mod download
    - go test ./...
builds:
  - main: ./cmd/helm-docs
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goos:
      - darwin
      - linux
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
- artifacts: checksum
  args: ["-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

nfpms:
- vendor: helm-docs
  homepage: https://github.com/norwoodj/helm-docs
  maintainer: norwoodj
  description: A tool for automatically generating markdown documentation for helm charts
  license: GNU General Public License v3.0
  formats:
  - deb
  - rpm
  replacements:
    amd64: x86_64
    linux: Linux

brews:
  - tap:
      owner: norwoodj
      name: homebrew
    folder: Formula
    homepage: https://github.com/norwoodj/helm-docs
    description: Automatically generate markdown documentation for helm charts
    install: |
      bin.install "helm-docs"
    test: |
      system "#{bin}/helm-docs --version"
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - jnorwood/{{ .ProjectName }}:{{ .Tag }}-amd64
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64
  - goos: linux
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
    image_templates:
      - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64v6
  - goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
    image_templates:
      - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64v7
docker_manifests:
- name_template: jnorwood/{{ .ProjectName }}:{{ .Tag }}
  image_templates:
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-amd64
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64v6
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64v7
- name_template: jnorwood/{{ .ProjectName }}:latest
  image_templates:
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-amd64
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64v6
    - jnorwood/{{ .ProjectName }}:{{ .Tag }}-arm64v7
