# image -- Image map
image:
  # image.registry -- Image registry
  registry: docker.io
  # image.repository -- Image repository
  repository: lucernae/django-sample
  # image.tag -- Image tag
  tag: "3.1"
  # image.pullPolicy -- Image pullPolicy
  pullPolicy: IfNotPresent

# labels -- (map) The deployment label
# @notationType -- yaml
labels:
  user/workload: "true"
  client-name: "my-boss"
  project-name: "awesome-project"
