apiVersion: v1
name: comment-ignored
description: A simple chart that installs, let's say PrometheusRules, that contains values.yaml comment that shouldn't be included in the helm-docs
version: "0.2.0"
home: "https://github.com/norwoodj/helm-docs/tree/master/example-charts/comment-ignored"
sources: ["https://github.com/norwoodj/helm-docs/tree/master/example-charts/comment-ignored"]
engine: gotpl
maintainers:
  - email: norwood.john.m@gmail.com
    name: John Norwood
