#!/usr/bin/env bash

function main {
    local release_version=${1:-}

    if [[ -z "${release_version}" ]]; then
        echo "Usage ${0} <release-version>"
        exit 1
    fi

    if ! [[ "${release_version}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "Release version must be of the form 'v1.2.3'"
        exit 1
    fi
    go install github.com/mikefarah/yq/v4@latest # Install yq via go
    
    # Update the docker image version for helm-docs-container pre-commit hook to release_version
    yq "(.[] | select(.id == \"helm-docs-container\")).entry = \"jnorwood/helm-docs:${release_version}\"" -i .pre-commit-hooks.yaml
    
    # Update the repo's pre-commit hook for helm-docs to release_version
    yq "(.repos[] | select(.repo == \"https://github.com/norwoodj/helm-docs\")).rev = \"${release_version}\"" -i .pre-commit-config.yaml

    git commit -am "Release ${release_version}" --allow-empty
    git cliff --tag "${release_version}" -o
    git commit --amend -a
    git tag "${release_version}"
}

main "${@}"
