name: Build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          #go-version-file: go.mod
          go-version: 'stable'

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master # don't pin, so the latest is pulled in
        with:
          args: '-exclude G304 ./...'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          args: release --snapshot --skip=sign

      - name: Verify chart diffs
        run: ./scripts/check-example-charts-diff

      - name: Cleanup
        if: always()
        run: rm -f ${HOME}/.docker/config.json
