name: Build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude G304 ./...'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7.1.0
        with:
          args: release --snapshot --skip=sign

      - name: Verify chart diffs
        run: ./scripts/check-example-charts-diff

      - name: Cleanup
        if: always()
        run: rm -f ${HOME}/.docker/config.json
